
- name: start seeding
  shell: SCREENRC=/dev/null SYSSCREENRC=/dev/null screen -dms 'seeder-{{ tag }}' python {{ remote_murder_path }}/murder_client.py seeder '{{ filename }}.torrent' '{{ filename }}' {{ ansible_default_ipv4['address'] }}
  tags: start_seeding
